version: '3.8'
 
services:
    mysql-db:
        platform: linux/x86_64
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=fnstyle
            - MYSQL_USER=user
        ports:
            - "3306:3306"
    web:
        build: .
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8100:80'
        restart: always
        environment:
            PMA_HOST: mysql-db
        depends_on:
            - mysql-db

            
volumes:
  fnstyle-db: 